### ISSUE TITLE
Error: Command failed: xdg-open http://localhost/

### ISSUE THREAD

**Issue by Morgy93** [scandipwa/create-magento-app#57]
### Describe the bug

On `npm run start`:
```
✔ Opening browser
node:child_process:397
      ex = new Error('Command failed: ' + cmd + '\n' + stderr);
           ^

Error: Command failed: xdg-open http://localhost/
/bin/sh: 1: xdg-open: not found

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'xdg-open http://localhost/'
}
```

![image](https://user-images.githubusercontent.com/7961978/152549222-498f79bd-16bc-4cd2-9004-28f610703d45.png)

### Did you try recovering your dependencies?

I did nothing special, but I think this should not happen with initial setup.

### Environment

WSL2 Ubuntu

### Steps to reproduce

Basically, just follow <https://docs.create-magento-app.com/getting-started/getting-started> using WSL2 Ubuntu.

### Expected behavior

That xdg-open gets installed automatically at some point.

### Actual behavior

It was not installed and so the error was thrown.

**Comment by ejnshtein** [comment]
Hi!

Thanks for the report!

Looks like your installation is borked or smth, because I haven't encountered such error myself, plus this cli application is not installable through apt and it looks like on WSL2 it requires some workarounds to function like what is discussed in [this thread on reddit](https://www.reddit.com/r/bashonubuntuonwindows/comments/gv5h07/how_to_get_xdgopen_to_work_in_wsl_2/).
