### ISSUE TITLE
Remove create-magento-app with all dependencies

### ISSUE THREAD

**Issue by Morgy93** [scandipwa/create-magento-app#61]
### Is your proposal related to a problem?

I'd love to get rid of `create-magento-app` with ALL dependencies it installed automatically. (cmake, build-essentials, etc.)
Currently there's no feature for that, not even a list for all things that belong to this app. (So one could remove manually)

### Describe the solution you'd like

I'd love to have some command or documentation to get rid of all things that came with `create-magento-app`.
The <https://docs.create-magento-app.com/getting-started/available-commands/cleanup> does not cover things installed on the host like cmake etc.

### Describe alternatives you've considered

Searched the docs and repo to get a clue about what this project is using. See what has been installed / modified on the system lately.

**Comment by ejnshtein** [comment]
Hi!

Thanks for the report!

`cleanup` command was not made for uninstalling CMA, rather removing the desired project cleanly. It was removed from the script template because it was considered dangerous if someone unintentionally tried to remove his Magento project will all data gone.

As for uninstalling dependencies, all dependencies are listed on the [requirements page](https://docs.create-magento-app.com/getting-started/prerequisites/installation-on-linux) and you can copy them and run them with the command `apt remove`. Plus, add `phpbrew` which is installed in `/usr/local/bin` and Docker, which is installed using [convenience script](https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script) and you can remove it by running commands in [Uninstall Docker Engine](https://docs.docker.com/engine/install/ubuntu/#uninstall-docker-engine) section.
